package ingredient;

public enum IngredientType {
    // Pizza ingredients:
    THICK_DOUGH, THIN_DOUGH, PLUM_TOMATO_SAUCE, MARINARA_SAUCE,
    MOZARELLA_CHEESE, REGGIANO_CHEESE, GREEK_CHEESE, PARMESAN_CHEESE,
    FROZEN_CLAM, FRESH_CLAM, ANCHOES, PINEAPPLE, OLIVE, BROCCOLI, ASPARAGUS,
    TOMATO_SLICES, HAM, SALAME, PEPPERONI, SPICY_SAUCE,
    // Lasagna ingredients:
    LASAGNA_NOODLES, MEAT, GARLIC, OREGANO,

}
